import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "tertiary": "#000000",
        "surface-dim": "#dbdad6",
        "error": "#ba1a1a",
        "primary": "#000000",
        "on-secondary-container": "#6f1a00",
        "surface-container": "#efeeea",
        "surface-container-highest": "#e3e2df",
        "surface": "#faf9f5",
        "surface-bright": "#faf9f5",
        "primary-fixed-dim": "#c1c8c2",
        "on-tertiary": "#ffffff",
        "outline": "#747874",
        "error-container": "#ffdad6",
        "primary-container": "#161d19",
        "on-primary-container": "#7e8680",
        "surface-variant": "#e3e2df",
        "on-tertiary-fixed": "#191d15",
        "background": "#faf9f5",
        "surface-container-high": "#e9e8e4",
        "surface-container-low": "#f4f4f0",
        "on-surface": "#1b1c1a",
        "secondary-container": "#fd7f5a",
        "on-primary-fixed-variant": "#414844",
        "inverse-surface": "#2f312e",
        "secondary-fixed": "#ffdbd1",
        "on-background": "#1b1c1a",
        "on-primary-fixed": "#161d19",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dde4dd",
        "tertiary-container": "#191d15",
        "on-tertiary-fixed-variant": "#44483f",
        "tertiary-fixed": "#e0e4d7",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#59605b",
        "outline-variant": "#c4c7c3",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c4c8bb",
        "inverse-on-surface": "#f2f1ed",
        "secondary": "#a43d1e",
        "on-surface-variant": "#434844",
        "secondary-fixed-dim": "#ffb5a0",
        "on-secondary-fixed-variant": "#832608",
        "on-tertiary-container": "#81857a",
        "inverse-primary": "#c1c8c2",
        "on-secondary-fixed": "#3b0900",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        unit: "4px",
        "margin-page": "40px",
        gutter: "24px",
        "stack-sm": "8px",
        "section-gap": "80px",
      },
      fontFamily: {
        "headline-md": ["DM Sans"],
        "label-caps": ["JetBrains Mono"],
        "headline-lg": ["DM Sans"],
        "data-ui": ["JetBrains Mono"],
        "body-md": ["Plus Jakarta Sans"],
        "display-xl": ["DM Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["DM Sans"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-ui": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
